package net.splatcraft.neoforge;

import com.mojang.logging.LogUtils;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import net.splatcraft.neoforge.command.SplatcraftClearInkCommand;
import net.splatcraft.neoforge.command.SplatcraftColorScoresCommand;
import net.splatcraft.neoforge.command.SplatcraftInkColorCommand;
import net.splatcraft.neoforge.command.SplatcraftReplaceColorCommand;
import net.splatcraft.neoforge.command.SplatcraftScanTurfCommand;
import net.splatcraft.neoforge.command.SplatcraftStageCommand;
import net.splatcraft.neoforge.command.SplatcraftSuperJumpCommand;
import net.splatcraft.neoforge.data.InkOverlayEvents;
import net.splatcraft.neoforge.data.SplatcraftData;
import net.splatcraft.neoforge.network.SplatcraftNetwork;
import net.splatcraft.neoforge.network.payload.PlayerSkinOverlayPayload;
import net.splatcraft.neoforge.network.payload.UseSubWeaponPayload;
import net.splatcraft.neoforge.network.payload.WeaponSettingsPayload;
import net.splatcraft.neoforge.player.SquidFormEvents;
import net.splatcraft.neoforge.player.SplatcraftInventoryEvents;
import net.splatcraft.neoforge.player.SplatcraftPlayerInfoEvents;
import net.splatcraft.neoforge.player.SplatcraftRespawnEvents;
import net.splatcraft.neoforge.registry.SplatcraftAttachments;
import net.splatcraft.neoforge.registry.SplatcraftAttributes;
import net.splatcraft.neoforge.registry.SplatcraftArmorMaterials;
import net.splatcraft.neoforge.registry.SplatcraftBlockEntities;
import net.splatcraft.neoforge.registry.SplatcraftBlocks;
import net.splatcraft.neoforge.registry.SplatcraftCriteriaTriggers;
import net.splatcraft.neoforge.registry.SplatcraftCreativeTabs;
import net.splatcraft.neoforge.registry.SplatcraftEntities;
import net.splatcraft.neoforge.registry.SplatcraftFeatures;
import net.splatcraft.neoforge.registry.SplatcraftGameRules;
import net.splatcraft.neoforge.registry.SplatcraftItems;
import net.splatcraft.neoforge.registry.SplatcraftLootFunctions;
import net.splatcraft.neoforge.registry.SplatcraftLootModifiers;
import net.splatcraft.neoforge.registry.SplatcraftMenuTypes;
import net.splatcraft.neoforge.registry.SplatcraftParticleTypes;
import net.splatcraft.neoforge.registry.SplatcraftRecipeSerializers;
import net.splatcraft.neoforge.registry.SplatcraftSounds;
import net.splatcraft.neoforge.registry.SplatcraftStats;
import net.splatcraft.neoforge.scoreboard.SplatcraftScoreboardHandler;
import net.splatcraft.neoforge.worldink.InkSurfaceEffects;
import net.splatcraft.neoforge.worldink.WorldInkHandler;
import net.splatcraft.neoforge.worldink.WorldInkSync;
import org.slf4j.Logger;

@Mod(Splatcraft.MOD_ID)
public final class Splatcraft {
    public static final String MOD_ID = "splatcraft";
    public static final Logger LOGGER = LogUtils.getLogger();

    public Splatcraft(IEventBus modEventBus, ModContainer modContainer) {
        SplatcraftBlocks.register(modEventBus);
        SplatcraftGameRules.init();
        SplatcraftArmorMaterials.register(modEventBus);
        SplatcraftItems.register(modEventBus);
        SplatcraftAttributes.register(modEventBus);
        SplatcraftAttachments.register(modEventBus);
        SplatcraftBlockEntities.register(modEventBus);
        SplatcraftEntities.register(modEventBus);
        SplatcraftFeatures.register(modEventBus);
        SplatcraftMenuTypes.register(modEventBus);
        SplatcraftRecipeSerializers.register(modEventBus);
        SplatcraftSounds.register(modEventBus);
        SplatcraftParticleTypes.register(modEventBus);
        SplatcraftLootFunctions.register(modEventBus);
        SplatcraftLootModifiers.register(modEventBus);
        SplatcraftCriteriaTriggers.register(modEventBus);
        SplatcraftCreativeTabs.register(modEventBus);
        modEventBus.addListener(SplatcraftNetwork::registerPayloadHandlers);
        modEventBus.addListener(SplatcraftStats::register);
        modEventBus.addListener(SplatcraftItems::registerDispenserBehaviors);
        modEventBus.addListener(SplatcraftItems::addCreativeTabSearchItems);
        NeoForge.EVENT_BUS.addListener(SplatcraftData::addReloadListeners);
        NeoForge.EVENT_BUS.addListener(WeaponSettingsPayload::onDatapackSync);
        NeoForge.EVENT_BUS.addListener(InkOverlayEvents::onEntityTick);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onLivingDeath);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onLivingDamagePre);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onLivingDrops);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onPlayerClone);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onEntityInteract);
        NeoForge.EVENT_BUS.addListener(SplatcraftInventoryEvents::onLeftClickBlock);
        NeoForge.EVENT_BUS.addListener(SplatcraftRespawnEvents::onPlayerRespawnPosition);
        NeoForge.EVENT_BUS.addListener(SplatcraftPlayerInfoEvents::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(SplatcraftSuperJumpCommand::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(UseSubWeaponPayload::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onPlayerTick);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onEntitySize);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onLivingVisibility);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onLivingFall);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onLivingJump);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onBreakSpeed);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onPlayerChangeGameMode);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onPlayerAttackEntity);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onRightClickItem);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onEntityInteract);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onEntityInteractSpecific);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onLeftClickBlock);
        NeoForge.EVENT_BUS.addListener(WorldInkHandler::onNeighborNotify);
        NeoForge.EVENT_BUS.addListener(WorldInkHandler::onRightClickBlock);
        NeoForge.EVENT_BUS.addListener(WorldInkHandler::onLevelTick);
        NeoForge.EVENT_BUS.addListener(InkSurfaceEffects::onPlayLevelSoundAtEntity);
        NeoForge.EVENT_BUS.addListener(InkSurfaceEffects::onPlayLevelSoundAtPosition);
        NeoForge.EVENT_BUS.addListener(InkSurfaceEffects::onLivingFall);
        NeoForge.EVENT_BUS.addListener(InkSurfaceEffects::onEntityTick);
        NeoForge.EVENT_BUS.addListener(WorldInkSync::onChunkSent);
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftStageCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftInkColorCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftColorScoresCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftClearInkCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftReplaceColorCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftScanTurfCommand.register(event));
        NeoForge.EVENT_BUS.addListener((RegisterCommandsEvent event) -> SplatcraftSuperJumpCommand.register(event));
        NeoForge.EVENT_BUS.addListener(SplatcraftScoreboardHandler::onServerStarted);
        NeoForge.EVENT_BUS.addListener(SplatcraftPlayerInfoEvents::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(SplatcraftPlayerInfoEvents::onPlayerChangedDimension);
        NeoForge.EVENT_BUS.addListener(SplatcraftPlayerInfoEvents::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(SplatcraftPlayerInfoEvents::onStartTracking);
        NeoForge.EVENT_BUS.addListener(PlayerSkinOverlayPayload::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(UseSubWeaponPayload::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(InkOverlayEvents::onStartTracking);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(SquidFormEvents::onPlayerChangedDimension);
        NeoForge.EVENT_BUS.addListener(SplatcraftSuperJumpCommand::onPlayerLoggedOut);
        NeoForge.EVENT_BUS.addListener(SplatcraftSuperJumpCommand::onPlayerChangedDimension);
        NeoForge.EVENT_BUS.addListener(SplatcraftSuperJumpCommand::onPlayerRespawn);
        modContainer.registerConfig(ModConfig.Type.CLIENT, SplatcraftConfig.SPEC);
    }
}
